- hosts: all
  vars_files:
    - secrets.yaml
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Run bot docker service
      docker_swarm_service:
        name: mic-self-development-routes-bot
        image: twobrowin/mic-self-development-routes-bot:1.1.0
        env:
          TZ: "Europe/Moscow"
          
          BOT_TOKEN:       "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"
          SHEETS_LINK:     "{{ sheets_link }}"

          SWITCH_UPDATE_TIME:   '15'
          SETTINGS_UPDATE_TIME: '35'
